version: '3.3'
services:
  rtmp:
    build: ./rtmp
    # Mapping from our computer ports to the ports in the Docker image.
    ports:
      - '1935:1935'
      - '8086:8080'
    container_name: rtmp_server_angular
    # Map HLS folder to a "data" folder on our computer.
    # This is to check the generated HLS segments.
    volumes:
      - ./data:/tmp/hls
      - ./rtmp/keys:/tmp/keys
      # - ./rtmp/testing/keytest/keys:/tmp/keytest

# Not going to expose any ports because
# the auth server should only be used by the
# RTMP server and not some potential malicious
# third party.
  auth:
    build: ./auth
    container_name: auth_server_angular                                                       